### ISSUE TITLE
NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by dlras2** [juancarlospaco/css-html-js-minify#43] opened 2016-10-10 14:36 UTC
I am getting the following error when trying to run the `process_single_css_file` function:

```
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    process_single_css_file('templates/styles/cards.css')
  File "C:\Users\<user>\AppData\Local\Continuum\Anaconda3\envs\<env>\lib\site-packages\css_html_js_minify\minify.py", line 120, in process_single_css_file
    log.info("Processing CSS file: {0}.".format(css_file_path))
NameError: name 'log' is not defined
```

My Python version is `Python 3.5.2 :: Continuum Analytics, Inc.`

I don't see anything about this requirement or setup step in the project's examples, and it would be nice if the logging failed gracefully.

**Comment by juancarlospaco** [comment] 2016-10-10 15:33
But which version of css-html-js-minify are you using ?
The one directly from git master may not be always ready...

**Comment by dlras2** [comment] 2016-10-10 15:36
Sorry for not specifying. I am using the one installed via `pip install css-html-js-minify`:

`Successfully installed css-html-js-minify-2.0.2`

**Comment by juancarlospaco** [comment] 2016-10-10 19:34
*It should be fixed now...*

- If using the functions as an API instead of as an App itself, you must have a working instance of a `logging.logger` named as `log` so the functions can do stuff like `log.info()`, because `print()` fails with Unicode under certain circumstances.
- We officially support the official CPython, not customs third party versions.

**Comment by Mil0R** [comment] 2017-05-27 09:45
@juancarlospaco `logging.logger named as log` , how?

**Comment by juancarlospaco** [comment] 2017-05-30 01:43
`import logging as log`

**Comment by Mil0R** [comment] 2017-05-31 02:14
@juancarlospaco I tried it but not worked, I am using it in aws lambda function.

**Comment by juancarlospaco** [comment] 2017-05-31 03:25
Post the whole Traceback.
Post the whole code if possible, or a meaningful part, or make a tiny example that reproduces the bug.

**Comment by csk007** [comment] 2017-06-07 14:56
Hey I faced the same issue when using the library through API

Traceback (most recent call last):
  File "codeObfuscator.py", line 67, in <module>
    MinifyCss(output_file)
  File "codeObfuscator.py", line 44, in MinifyCss
    css_html_js_minify.process_single_css_file(ip_file, overwrite=output_file_overwrite)
  File "/usr/local/lib/python3.5/dist-packages/css_html_js_minify/minify.py", line 120, in process_single_css_file
    log.info("Processing CSS file: {0}.".format(css_file_path))
NameError: name 'log' is not defined

**Comment by juancarlospaco** [comment] 2017-06-07 16:21
Add at the top:
`import logging as log`

**Comment by niklasp** [comment] 2017-06-16 22:04
i have the same error in the most recent version. I had to
```
pip install git+git://github.com/juancarlospaco/css-html-js-minify.git@609f9901031d219a95f81776c8b81317993a60d3
```

**Comment by juancarlospaco** [comment] 2017-08-16 12:13
WIP Fix for this is on active Development, we hope to have it ASAP, but its happening somewhere else:
https://github.com/juancarlospaco/anglerfish#angler

**Comment by datamafia** [comment] 2017-12-28 03:15
I am getting the same log error, same message, same scenario.

Despite the addition of `import logging as log` and variations, the simplest code that follows above recommendations is a fail:

```
import logging as log
from css_html_js_minify import process_single_css_file
process_single_css_file('path/to.css')
```

delivering:

```
...site-packages/css_html_js_minify/minify.py", line 120, in process_single_css_file
    log.info("Processing CSS file: {0}.".format(css_file_path))
NameError: name 'log' is not defined
```

In looking at the source I would like to ask why `import logging as log` is not on the project source?  

As I am sure there is a good reason why.

So how about the ability to pass in `log=log` as an arg?  

This package really looks good and solves a legit problem for our project (thanks for your work), but I must confess that I am at a loss to get this working as delivered.

I am able to get the script working by adding  `import logging as log` to the package in the correct place. Works amazing, really great package.  I don't want to edit packages (prod will not allow regardless).  How are other people adding this to the stack and getting around this problem?

```
Version 2.2.2
Python 3.6.0
```

**Comment by juancarlospaco** [comment] 2018-04-14 14:36
Fixed on master.

**Closed by juancarlospaco** 2018-04-14 14:36 UTC
Labels: duplicate, help wanted, invalid, question, wontfix
