### ISSUE TITLE
Confusion: Single file?

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#38] opened 2016-07-02 01:14 UTC
I've put off trying to upgrade to the latest versions as for the last few releases it seems that all the functions of this script have been split up into multiple files.

What happened to the single file that was included in every release? I presumed that the single file approach was more for people who wanted to add it to their build pipeline without needing to rely on much fiddling <- c'est moi.

I'm fine if there was a reason for the change but I couldn't find any documentation as to why.

**Comment by juancarlospaco** [comment] 2016-07-02 04:57
https://github.com/juancarlospaco/css-html-js-minify/issues/23
https://github.com/juancarlospaco/css-html-js-minify/pull/31
https://github.com/juancarlospaco/css-html-js-minify/commit/3f3e00daf7eaf510964c5c610c6740b5d7ef9c35
https://github.com/juancarlospaco/css-html-js-minify/commit/6eb53baad96245e61f9959d12e2b4d4b051a3915

I wanted to have it single file, but community sent commits to split it up.
The code remain the same more or less anyways...

Feel free to send any commit that you think may improve the use case you mention.

**Comment by Omniferum** [comment] 2016-07-02 05:05
I can understand their reasoning for splitting, but the main appeal of this for me (and as said on this project's page) is that it is a simple:

C:\Python\Py.exe css-html-js-minify.py original.css compressed.css

Basically I can't do that anymore. I suspect one would have to run the setup.py but that was never a requirement before and half the beauty of python is simple portability.

If it is just a general case of merging is it possible to just have a separate file that does this included in the commit?
e.g.
css-html-js-minify-merged.py

**Comment by juancarlospaco** [comment] 2016-07-02 07:53
Yes.
Feel free to re-merge again into single-file, because it was a by-product of making it usable as a python module.

**Comment by mverleg** [comment] 2016-07-03 14:10
I wanted to have a look but in Python3 this works for me (latest version of the code 469688b3f07c8a9f1f2713c76433130c0191fbe1, not installed using pip):

    python ~/css-html-js-minify/css-html-js-minify.py bla.css

If it doesn't, maybe we can get it to work with ``python -m css-html-js-minify`` and relative imports. Alternatively we could do some sys.path magic or merge everything, but it wouldn't help clarity I think.

(Although this is still a valid use case, I'd recommend trying pip for installing anyway; it's hard to imagine there's any less fiddly way than just ``pip install css-html-js-minify``.)

**Comment by Omniferum** [comment] 2016-07-03 14:28
Should perhaps point out that I am a windows user. Specific error messages are as follows.

Traceback (most recent call last):
  File "css-html-js-minify.py", line 11, in <module>
    from css_html_js_minify.minify import prepare, main
  File "css_html_js_minify\__init__.py", line 11, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "css_html_js_minify\minify.py", line 28, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
ImportError: No module named 'anglerfish'

**Comment by juancarlospaco** [comment] 2016-07-03 21:42
I mean we can prepare a `*.PYZ` file of the current code, it should be kind of easy...

**Comment by mverleg** [comment] 2016-07-04 10:43
It seems the problem is not so much that there are multiple files in this project, but that the project depends on ``anglerfish``. Right? I suppose the only solution for that is including (part of) it in this project, but unless it's very small I don't think it's advisable.

**Comment by juancarlospaco** [comment] 2016-07-04 15:30
You can make a `*.PYZ` for each one, and it should be ok. Starting with this one.

**Comment by Omniferum** [comment] 2016-07-04 15:34
Actually my concern was far more to do with the fact that it is not just one single file. The anglerfish error was actually new. Before it was some sort of import __main error.

I'm just curious because it now seems like the project is more for modular usage rather than just giving someone one file and away they go, whereas before it was different. Why not just have a folder labelled 'modules/modular' that has them all split up and as part of the commit have the regular single .py?

**Comment by juancarlospaco** [comment] 2016-07-04 16:07
Thats what Im saying PYZ can be a folder or a bunch of files still be a single file.

**Comment by Omniferum** [comment] 2016-07-04 16:09
Apologies. My own ignorance there.

**Comment by juancarlospaco** [comment] 2016-07-04 16:38
We will work to improve the software as needed, 
at some point I think making it work as a python module is useful too.

Feel free to contribute, here or on anglerfish...
d-( ʘ‿ʘ )_m

**Comment by juancarlospaco** [comment] 2016-12-13 04:46
Everything needed to make it single-file is here:
https://github.com/juancarlospaco/css-html-js-minify/blob/master/setup.py#L71
http://devdocs.io/python~3.5/library/zipapp#zipapp.create_archive
`python setup.py zipapp`

Closing this since its done...

**Comment by Omniferum** [comment] 2016-12-15 02:55
Before I start spending hours scouring how to identify this I wanted to see if it was at all relevant here as it is directly related to this topic.

[code]
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    'Topic :: Software Development',
  File "c:\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 84, in run
    create_archive(tmpdir, 'css-html-js-minify.pyz', '/usr/bin/env python3', "css-html-js-minify")
  File "c:\Python35\lib\zipapp.py", line 116, in create_archive
    "Cannot specify entry point if the source has __main__.py")
zipapp.ZipAppError: Cannot specify entry point if the source has __main__.py
[/code]

**Closed** 2018-04-14 12:28 UTC
Labels: help wanted, question
